# Generated by Django 4.2.20 on 2025-04-07 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='ordinal_number',
            field=models.IntegerField(),
        ),
    ]
