# Generated by Django 4.2.20 on 2025-04-10 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_alter_place_description_long'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['ordinal_number']},
        ),
        migrations.AlterUniqueTogether(
            name='place',
            unique_together={('title', 'lng', 'lat')},
        ),
    ]
