# Generated by Django 4.2.20 on 2025-04-13 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_alter_image_options_alter_place_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['ordinal_number'], 'verbose_name': 'Фотография', 'verbose_name_plural': 'Фотографии'},
        ),
        migrations.AlterModelOptions(
            name='place',
            options={'verbose_name': 'Место', 'verbose_name_plural': 'Места'},
        ),
    ]
