# Generated by Django 4.2.20 on 2025-04-13 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_alter_image_options_alter_place_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='title',
            field=models.CharField(max_length=150),
        ),
    ]
