# Generated by Django 4.2.20 on 2025-04-13 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0009_rename_description_long_place_long_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='ordinal_number',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
